### ISSUE TITLE
build(cicd): 🏗️ workflow 'assign-author' to issue or pr

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#268]
## Description

Add workflow 'assign-author' to ISSUE or PR, assigning author automatically.

## Code example

```yaml
name: Auto Author Assign

on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]

permissions:
  issues: write
  pull-requests: write

jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@v2.1.1

```

## Tasks

- [x] create worfklow
- [x] merge PR
- [x] test on next issue and PR if all works as expected
