### ISSUE TITLE
cicd(prettier): ⚙️ formatting - workflow setup

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#349]
## Description

This refactoring focuses on setting up a GitHub Actions workflow to run Prettier on pull requests, ensuring consistent code formatting across the repository.

## Benefits

- Improve overall code quality.

## Refactoring Plan

- Create a new workflow file `prettier.yml` in the `.github/workflows` directory.
- Define the workflow to trigger on pull requests to the `master` branch.
- Set up the job to run on the latest version of Ubuntu.
- Include steps to check out the repository, set up the Node.js environment, install dependencies, and run Prettier.

## Links

- [Reference to the Prettier documentation.](https://prettier.io/)
- [Link to the GitHub Actions documentation](https://github.com/features/actions).

## Code Example

Provide a code example if applicable.

```yaml
name: Prettier

on:
  pull_request:
    branches:
      - master

jobs:
  run-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npm run prettier:check
```

## Tasks

- [x] Create the `prettier.yml` workflow file.
- [x] Define the trigger for pull requests to the `master` branch.
- [x] Install dependencies and run Prettier.

## Acceptance Criteria

- [x] Functionality remains unchanged.
- [x] All tests pass successfully.
- [x] Code is reviewed and approved through PR.

## Screenshots

Attach relevant screenshots if applicable.

### Before

- no checks
- with Prettier console shows = error ⛔ 

![Image](https://github.com/user-attachments/assets/2d38bf2f-c338-4b40-9c29-ec8fd7028835)

### After

- code can be formatted on localhost
- then code formatting check is = Passing ✅

![Image](https://github.com/user-attachments/assets/591168dd-8e38-43da-b642-d9649e1e0b04)
