### ISSUE TITLE
BUN - investigate bunfig.toml

### ISSUE THREAD

**Issue by krsiakdaniel** [krsiakdaniel/portfolio-website-krsiak-cz#527]
### JSX Configuration
Since you're using React and TypeScript, you can configure how Bun handles JSX:
```toml
jsx = "react"
jsxFactory = "React.createElement"
jsxFragment = "React.Fragment"
jsxImportSource = "react"
```
This ensures that Bun correctly processes JSX syntax in your project.

### Preload Scripts/Plugins
If you have any scripts or plugins that need to be executed before running your project, you can specify them in the `preload` field:
```toml
preload = ["./scripts/preload.ts"]
```
This could be useful for setting up environment variables or initializing certain configurations.

### Log Level
For better debugging, you can set the log level to "debug":
```toml
logLevel = "debug"
```

### Package Management
Ensure that optional dependencies and development dependencies are installed:
```toml
[install]
optional = true
dev = true
```

### Custom Loader
If you have custom file extensions that need to be loaded as TypeScript or JSX, you can configure the loader:
```toml
[loader]
".bagel" = "tsx"
```

### Telemetry
If you want to disable telemetry for privacy reasons:
```toml
telemetry = false
```

### Test Runner Configuration
You can also configure Bun's test runner for your project:
```toml
[test]
root = "./tests"
preload = ["./tests/setup.ts"]
coverage = true
coverageThreshold = { line = 0.8, function = 0.8, statement = 0.9 }
coverageReporter  = ["text", "lcov"]
```

### Example `bunfig.toml` for Your Project
Here's an example `bunfig.toml` that combines these configurations:
```toml
# JSX Configuration
jsx = "react"
jsxFactory = "React.createElement"
jsxFragment = "React.Fragment"
jsxImportSource = "react"

# Preload Scripts/Plugins
preload = ["./scripts/preload.ts"]

# Log Level
logLevel = "debug"

# Package Management
[install]
optional = true
dev = true

# Custom Loader
[loader]
".bagel" = "tsx"

# Telemetry
telemetry = false

# Test Runner Configuration
[test]
root = "./tests"
preload = ["./tests/setup.ts"]
coverage = true
coverageThreshold = { line = 0.8, function = 0.8, statement = 0.9 }
coverageReporter  = ["text", "lcov"]
```
